#!/usr/bin/env python3
"""publish_component — the virtual-monorepo publishing bot.

During the component-world transition the MONOREPO stays the single source of
truth for the code; each graduated component is *published* from it into its own
`sciqnt/<repo>` (the k8s publishing-bot model). This script regenerates one
component's standalone repo tree from its in-mono package and — crucially —
**verifies it installs clean in an isolated venv and passes its tests**, which is
the guarantee the runbook calls out as "not off-the-shelf, build it"
(`sq-constitution/MIGRATION.md`, Phase 2 / honest residuals).

It is deterministic and idempotent: run it, review the git diff in the target
repo, commit, push. The target's own inherited CI re-verifies on push.

    python scripts/publish_component.py sq-schema            # generate + verify
    python scripts/publish_component.py sq-schema --no-verify # skip the venv check

Adding a component = add a SPEC entry. The first (sq-schema) is the contract hub.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import venv
from pathlib import Path

MONO = Path(__file__).resolve().parent.parent
CONSTITUTION = Path.home() / "Projects/sciqnt-org/sq-constitution"   # caller-templates source
DEFAULT_TARGET_ROOT = Path.home() / "Projects/sciqnt-org"


class Spec:
    """One component's publish recipe: where its code/tests live in the mono and
    how the standalone distribution is described."""

    def __init__(self, repo, dist, import_name, pkg_dir, tests, description, role):
        self.repo = repo                  # sciqnt/<repo> short name, e.g. "sq-schema"
        self.dist = dist                  # PyPI distribution, e.g. "sciqnt-schema"
        self.import_name = import_name    # python import, e.g. "sq_schema"
        self.pkg_dir = MONO / pkg_dir     # the package dir in the mono
        self.tests = [MONO / t for t in tests]   # test files to carry over
        self.description = description
        self.role = role                  # topic/manifest role, NOT in the repo name


SPECS = {
    "sq-schema": Spec(
        repo="sq-schema",
        dist="sciqnt-schema",
        import_name="sq_schema",
        pkg_dir="core/sq_schema",
        tests=["core/tests/test_schema.py", "core/tests/test_contract_schema.py"],
        description="sq-schema — the canonical cross-asset contract for sciqnt "
                    "(point-in-time-correct schema + conformance + JSON-Schema artifact).",
        role="contract-hub",
    ),
}

PYPROJECT = """\
# GENERATED by sciqnt/sciqnt scripts/publish_component.py — do not hand-edit during
# the transition; edit core/{import_name} in the monorepo and re-publish.
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "{dist}"
dynamic = ["version"]                 # single source: {import_name}.__version__
description = "{description}"
readme = "README.md"
requires-python = ">=3.10"
license = {{ text = "MIT" }}
authors = [{{ name = "sciqnt" }}]
dependencies = [
    "pydantic>=2.5,<3",
]

[project.urls]
Homepage = "https://github.com/sciqnt/{repo}"
Source = "https://github.com/sciqnt/{repo}"

[tool.setuptools]
package-dir = {{ "" = "src" }}
packages = ["{import_name}"]

[tool.setuptools.dynamic]
version = {{ attr = "{import_name}.__version__" }}

[tool.setuptools.package-data]
{import_name} = ["contract.schema.json"]
"""

README = """\
# {repo} · `{dist}`

{description}

> **Published from the monorepo.** During the component-world transition this repo
> is *generated* from [`sciqnt/sciqnt`](https://github.com/sciqnt/sciqnt)
> (`core/{import_name}`) by its publishing bot. The monorepo is the source of truth
> until the contract has fully graduated; **edit there**, not here. Role: `{role}`.

## Install

```bash
pip install {dist}
```

## What it is

The thin, stable **contract** every sciqnt connector translates *into* and every
consumer reads *from* — never broker JSON. Money is `Decimal`; every fact is
bitemporal (`valid_at` + `observed_at`). This package computes no P/L — adapters
fill the fields, consumers read them.

The contract is also published as a **language-agnostic JSON-Schema artifact**,
[`contract.schema.json`](src/{import_name}/contract.schema.json), so a connector in
any language — or a reviewing agent — can read and diff it. Regenerate it from the
models with `python -m {import_name}.json_schema --write`; CI fails if it drifts.

## Governance

Inherits the org's reusable workflows (CI, principle-review, @claude, issue-triage)
from [`sciqnt/sq-constitution`](https://github.com/sciqnt/sq-constitution). Licensed
MIT; contributions are DCO sign-off, never a CLA.
"""

MANIFEST = """\
# Component manifest — machine-readable identity (role lives HERE, not in the name).
name: {dist}
import: {import_name}
repo: sciqnt/{repo}
role: {role}
contract: self        # this IS the contract; other components pin a version of it
published_from: sciqnt/sciqnt   # virtual-monorepo source of truth (transition)
license: MIT
"""

GITIGNORE = "__pycache__/\n*.pyc\nbuild/\ndist/\n*.egg-info/\n.venv/\n"


def _reset_tree(target: Path):
    """Clear the GENERATED parts of the target, preserving .git and anything
    we don't own (so a human-added file in the repo isn't nuked silently)."""
    for rel in ("src", "tests", ".github/workflows", "pyproject.toml",
                "README.md", "CHANGELOG.md", "manifest.yaml", "LICENSE", ".gitignore"):
        p = target / rel
        if p.is_dir():
            shutil.rmtree(p)
        elif p.exists():
            p.unlink()


def _copy_package(spec: Spec, target: Path):
    dst = target / "src" / spec.import_name
    dst.mkdir(parents=True, exist_ok=True)
    for f in sorted(spec.pkg_dir.iterdir()):
        # Ship the package source + the contract artifact; skip build cruft and
        # the package's own pyproject/CHANGELOG (regenerated / relocated).
        if f.suffix == ".py" or f.name == "contract.schema.json":
            shutil.copy2(f, dst / f.name)
    # CHANGELOG lives at the repo root in the standalone layout.
    changelog = spec.pkg_dir / "CHANGELOG.md"
    if changelog.exists():
        shutil.copy2(changelog, target / "CHANGELOG.md")


def _copy_tests(spec: Spec, target: Path):
    dst = target / "tests"
    dst.mkdir(parents=True, exist_ok=True)
    (dst / "__init__.py").write_text("")
    for t in spec.tests:
        shutil.copy2(t, dst / t.name)


def _copy_workflows(target: Path):
    dst = target / ".github" / "workflows"
    dst.mkdir(parents=True, exist_ok=True)
    src = CONSTITUTION / "caller-templates"
    if not src.exists():
        raise SystemExit(f"caller-templates not found at {src} — clone sq-constitution first")
    for wf in sorted(src.glob("*.yml")):
        shutil.copy2(wf, dst / wf.name)


def _write_meta(spec: Spec, target: Path):
    fields = dict(repo=spec.repo, dist=spec.dist, import_name=spec.import_name,
                  description=spec.description, role=spec.role)
    (target / "pyproject.toml").write_text(PYPROJECT.format(**fields))
    (target / "README.md").write_text(README.format(**fields))
    (target / "manifest.yaml").write_text(MANIFEST.format(**fields))
    (target / ".gitignore").write_text(GITIGNORE)
    license_src = MONO / "LICENSE"
    if license_src.exists():
        shutil.copy2(license_src, target / "LICENSE")


def _verify_clean_install(spec: Spec, target: Path):
    """The publishing guarantee: a fresh venv, `pip install .`, tests pass against
    the INSTALLED package (not the mono's source tree)."""
    vdir = target / ".verify-venv"
    if vdir.exists():
        shutil.rmtree(vdir)
    venv.create(vdir, with_pip=True)
    py = vdir / ("Scripts" if os.name == "nt" else "bin") / "python"
    def run(args, **kw):
        return subprocess.run([str(py), *args], cwd=target, **kw)
    print("  · pip install . (isolated)")
    r = run(["-m", "pip", "install", "-q", "."], capture_output=True, text=True)
    if r.returncode:
        shutil.rmtree(vdir)
        raise SystemExit(f"clean-install FAILED:\n{r.stdout}\n{r.stderr}")
    print("  · unittest discover -s tests (against the installed package)")
    r = run(["-m", "unittest", "discover", "-s", "tests", "-p", "test_*.py"],
            capture_output=True, text=True)
    shutil.rmtree(vdir)
    # The build leaves transient artifacts in-tree (gitignored); clean them so a
    # rerun and the pushed tree stay pristine.
    for cruft in list(target.glob("build")) + list(target.rglob("*.egg-info")):
        if cruft.is_dir():
            shutil.rmtree(cruft)
    if r.returncode:
        raise SystemExit(f"standalone tests FAILED:\n{r.stdout}\n{r.stderr}")
    # unittest reports to stderr
    print("  ·", (r.stderr.strip().splitlines() or ["ok"])[-1])


def publish(name: str, target_root: Path, verify: bool = True) -> Path:
    spec = SPECS[name]
    target = target_root / spec.repo
    target.mkdir(parents=True, exist_ok=True)
    print(f"publishing {spec.repo} ({spec.dist}) → {target}")
    _reset_tree(target)
    _copy_package(spec, target)
    _copy_tests(spec, target)
    _copy_workflows(target)
    _write_meta(spec, target)
    print("  · tree generated")
    if verify:
        _verify_clean_install(spec, target)
        print("  · VERIFIED: installs clean + tests green in isolation")
    return target


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("component", choices=sorted(SPECS), help="component to publish")
    ap.add_argument("--target-root", type=Path, default=DEFAULT_TARGET_ROOT,
                    help="dir that holds the per-component repo checkouts")
    ap.add_argument("--no-verify", action="store_true",
                    help="skip the isolated clean-install + test verification")
    a = ap.parse_args()
    target = publish(a.component, a.target_root, verify=not a.no_verify)
    print(f"done → {target}")


if __name__ == "__main__":
    main()
